language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer update --prefer-source --dev

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml --group=Coverage
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests

after_script:
  - php vendor/bin/coveralls -v

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false
